export const OBTER_PROJETOS = "OBTER_PROJETOS"

export const CADASTRAR_PROJETOS = "CADASTRAR_PROJETOS"

export const ALTERAR_PROJETOS = "ALTERAR_PROJETOS"

export const ELIMINAR_PROJETOS = "ELIMINAR_PROJETOS"

export const OBTER_TAREFAS = "OBTER_TAREFAS"

export const CADASTRAR_TAREFAS = "CADASTRAR_TAREFAS"

export const ALTERAR_TAREFA = "ALTERAR_TAREFA"


